Repository kinneyan/bond-buddies, pull requests merged in 2024-03, with the labels that each got.

#9 Remove unnecessary import from register endpoint
  controllers/register.js
Labels: api

#10 Write login endpoint
  controllers/login.js
  routes/user.js
Labels: api

#8 Implement user api endpoints
  .gitignore
  controllers/login.js
  controllers/register.js
  frontend/.gitignore
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/components/PageTitle.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/logo.svg
  frontend/src/pages/LoginPage.js
  frontend/src/reportWebVitals.js
  frontend/src/setupTests.js
  package-lock.json
  package.json
  routes/user.js
  server.js
  utils/auth.js
  utils/database.js
  utils/hash.js
Labels: front-end, api

#13 Fix typo in server.js
  server.js
Labels: bug

#16 Return bad request when required body information cannot be processed
  controllers/login.js
  controllers/register.js
Labels: enhancement, api

#17 Move bearer to header
  controllers/login.js
  controllers/register.js
Labels: enhancement, api

#18 Change local express port
  server.js
Labels: back-end

#19 Move authorization token to response body
  controllers/login.js
  controllers/register.js
Labels: enhancement, api

#21 Set expire time on signed JWT tokens
  utils/auth.js
Labels: enhancement, api

#20 Implement unfriend endpoint
  controllers/removeFriend.js
  middleware/auth.js
  routes/friends.js
  server.js
Labels: enhancement, api

#22 Move middlware to routes
  routes/friends.js
  server.js
Labels: enhancement, api

#32 Change response status codes of API responses
  controllers/addFriend.js
  controllers/login.js
  controllers/register.js
  controllers/removeFriend.js
Labels: enhancement, api

#34 Implement getUser endpoint
  controllers/getUser.js
  routes/user.js
Labels: enhancement, api

#33 Remove debug console log
  controllers/addFriend.js
Labels: bug, api

#31 Implement update user
  controllers/updateUser.js
  routes/user.js
Labels: enhancement, api

#36 Update server field cases
  controllers/addFriend.js
  controllers/getUser.js
  controllers/login.js
  controllers/register.js
  controllers/removeFriend.js
  controllers/searchFriends.js
  controllers/updateUser.js
Labels: enhancement, back-end

#40 draft mobile app
  frontend/mobile/App.js
  frontend/mobile/app.json
  frontend/mobile/assets/adaptive-icon.png
  frontend/mobile/assets/favicon.png
  frontend/mobile/assets/fonts/Omnes Bold.ttf
  frontend/mobile/assets/fonts/Omnes Regular.ttf
  frontend/mobile/assets/fonts/Roboto Medium.ttf
  frontend/mobile/assets/fonts/Roboto Regular.ttf
  frontend/mobile/assets/icon.png
  frontend/mobile/assets/images/aero.png
  frontend/mobile/assets/images/aqua.png
  frontend/mobile/assets/images/mag.png
  frontend/mobile/assets/images/pyro.png
  frontend/mobile/assets/images/terra.png
  frontend/mobile/assets/splash.png
  frontend/mobile/babel.config.js
  frontend/mobile/components/AddFriend.js
  frontend/mobile/components/BorderGradient.js
  frontend/mobile/components/BottomMenu.js
  frontend/mobile/components/DISC.js
  frontend/mobile/components/FontLoader.js
  frontend/mobile/components/Friendship.js
  frontend/mobile/components/Gradient.js
  frontend/mobile/components/MyFriend.js
  frontend/mobile/components/Personality.js
  frontend/mobile/package-lock.json
  frontend/mobile/package.json
  frontend/mobile/screens/AssessmentScreen.js
  frontend/mobile/screens/ForgotScreen.js
  frontend/mobile/screens/FriendsScreen.js
  frontend/mobile/screens/HomeScreen.js
  frontend/mobile/screens/LoginScreen.js
  frontend/mobile/screens/QuestionScreen.js
  frontend/mobile/screens/RegisterScreen.js
  frontend/mobile/screens/SettingsScreen.js
  frontend/mobile/screens/UserScreen.js
Labels: enhancement, front-end

#43 Implement update assessment responses
  controllers/updateAssessments.js
  routes/assessments.js
  server.js
Labels: enhancement, api

#44 Api/block user
  controllers/blockUser.js
  routes/user.js
Labels: enhancement, api

#46 Add id checks
  controllers/addFriend.js
  controllers/getUser.js
  controllers/removeFriend.js
  controllers/updateUser.js
Labels: enhancement, api

#47 Fix authentication
  controllers/addFriend.js
  controllers/removeFriend.js
  middleware/auth.js
Labels: enhancement, api
